
# Reminder: variables are accessed via {{ site.myvariable }}.

### Website description
title: Sebastien Plat
url: "sebastienplat.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""                     # the subpath of your site, e.g. /blog
description:
  Personal blog discussing Data Science topics.

github_username:  sebastienplat
email: ""

### Setup
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

markdown: kramdown    # Kramdown is supported by Github
enable-mathjax: yes   # Mathjax setting
share: yes            # Change it to `no` to remove share buttons (setup in _includes)
 
### Misc
collections:
    authors:
        output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

